parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     null
    database_name:     tuto_symfony
    database_user:     root
    database_password: null

    mailer_transport:  gmail
    mailer_host:       "smtp.gmail.com"
    mailer_user:       jeandiasivi@gmail.com
    mailer_password:   Romains109

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    java_path: C:\Program Files (x86)\Java\jre7\bin\java.exe
    
    sdzblog.nombre_par_page: 5
    sdzblog.dest_email:      vous@vous.Com

    akismet_key: votre_cle
    akismet_url: votre_site