# J'ai sorti cette route afin de ne pas avoir le préfixe /blog lors de l'import
sdzblog_accueil:
    pattern:   /{page}
    defaults:  { _controller: SdzBlogBundle:Blog:index, page: 1 }
    requirements:
        page:  \d+

sdzblog_about:
    pattern:  /about
    defaults: { _controller: SdzBlogBundle:Page:about }
    requirements:
        _method:  GET
 
sdzblog_contact:
    pattern:  /contact
    defaults: { _controller: SdzBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST
